// eli15/chapters/consistency-modes.js
// Phase 1C (F4) — real content. Explains the three consistency modes
// that the query path in ruvectorBridge.js now honours.
export default {
  id: 'consistency-modes',
  title: 'Fresh, Eventual, Frozen — three ways training looks at the archive',
  oneLiner: 'Should every generation re-ask the archive "who looks like this track?", or lock in an answer? Three modes, one radio row.',
  body: [
    '<p>Every generation, the training loop asks the archive a question:',
    '<em>"Which past brains are most similar to the track I\'m about to run?"</em>',
    'That answer is a short list of brains the GA uses as warm seeds for the',
    'next batch of cars. The question sounds simple — but "what is the',
    'archive?" has more than one reasonable answer, because the archive is',
    '<strong>growing</strong> while you train. Every generation you just',
    'finished added new brains to it. So do you ask <em>the current archive</em>',
    'or <em>the archive as it was before you started</em>?</p>',

    '<h3>Three answers, one radio row</h3>',

    '<p><strong>Fresh</strong> — re-ask every generation. The retrieval',
    'always sees the newest brains, so as the GA discovers good ones they',
    'immediately become available as seeds. The downside: the answer can',
    '<em>wobble</em> mid-run. A new great brain landing in generation 7',
    'reshuffles the "who does this track look like?" ordering, which can',
    'make the seeds you get in generation 8 very different from what you',
    'got in generation 6. This is today\'s default and is what you want for',
    'everyday training.</p>',

    '<p><strong>Eventual</strong> — cache the answer for <code>N</code>',
    'generations (default 10), then re-ask. Cheaper, steadier. Between',
    're-asks the seed list is <em>frozen to a moving window</em> — you get',
    'some of the new-brain benefit but without the wobble. The tradeoff is',
    'latency of the "new good brain → seeds include it" path: a brain',
    'discovered in gen 7 with TTL=10 might wait until gen 17 to start',
    'influencing retrieval. Pick eventual when you want predictable seeds',
    'for longer comparisons without sacrificing growth entirely.</p>',

    '<p><strong>Frozen</strong> — at the moment you switch into frozen mode,',
    'the archive\'s current contents become the <em>entire</em> answer space',
    'for every subsequent query. Brains archived <em>after</em> the freeze',
    'are still saved (training continues normally), they just don\'t appear',
    'in <code>recommendSeeds</code> results until you thaw (by switching',
    'back to fresh or eventual). This is the mode the A/B baseline worker',
    'wants — without it, a side-by-side run where one canvas has ruvector',
    'and the other doesn\'t is a moving target because the "with" side',
    'keeps growing its archive.</p>',

    '<h3>Why frozen exists: the A/B race</h3>',
    '<p>The A/B toggle in this panel spawns a baseline sim-worker that runs',
    'the same track side-by-side. For the delta to be meaningful, both sides',
    'need to see <em>the same archive</em>. Without frozen mode, the',
    'ruvector side keeps adding brains each generation while the baseline',
    'does not — so "how much did ruvector help?" gets confounded with',
    '"how much did the archive grow?". Pinning the archive at frozen-mode',
    'entry time gives a clean single-variable comparison. The helper in',
    '<code>consistency/worker-sync.js</code> computes the payload a future',
    'version of <code>spawnB()</code> can postMessage to the baseline; the',
    'sim-worker has a matching <code>case \'freeze\'</code> handler ready to',
    'receive it.</p>',

    '<h3>What the tick strip is showing you</h3>',
    '<p>Under the radio row sits a horizontal strip of 30 tiny dots. Each',
    'dot pulses green-then-fades every time <code>recommendSeeds</code>',
    'actually ran a fresh query (cache miss). Watch it as you flip modes:</p>',
    '<ul>',
    '<li><strong>Fresh</strong>: every generation pulses one dot. Continuous',
    '    activity.</li>',
    '<li><strong>Eventual</strong>: the first query in a TTL window pulses;',
    '    the next 9 are silent (served from cache). You\'ll see a pulse,',
    '    then nine quiet ticks, then another pulse.</li>',
    '<li><strong>Frozen</strong>: queries still fire (the mode is "filter the',
    '    archive to the pinned set", not "skip searching entirely"), so the',
    '    strip keeps pulsing. What\'s different is that <em>results</em>',
    '    never include brains archived after the freeze — check the seed',
    '    list for the proof.</li>',
    '</ul>',

    '<h3>Try it yourself</h3>',
    '<ul>',
    '<li>Open the tests harness: <code>tests/consistency-modes-smoke.html</code>.',
    '    It asserts, among other things, that a brain inserted <em>after</em>',
    '    freeze doesn\'t appear in results until you thaw.</li>',
    '<li>Reload the page with <code>?consistency=frozen</code> in the URL to',
    '    boot straight into frozen mode — handy for reproducing an A/B run.</li>',
    '<li>Open the DevTools console and try',
    '    <code>window.__rvBridge.getConsistencyStats()</code> while training',
    '    to watch <code>cacheHits</code> tick up under Eventual.</li>',
    '</ul>',

    '<h3>Where this lives in the code</h3>',
    '<p>The state machine is <code>AI-Car-Racer/consistency/mode.js</code>.',
    'The bridge consumes it in <code>recommendSeeds</code> inside',
    '<code>ruvectorBridge.js</code> — look for the <em>1C — F4</em> comment',
    'block. The UI radio row + tick strip are in <code>uiPanels.js</code>;',
    'the A/B-worker helper is <code>consistency/worker-sync.js</code>.</p>',
  ].join('\n'),
  related: [
    'warm-restart',
    'track-similarity',
    'vectordb-hnsw',
  ],
};
