// eli15/chapters/ewc.js
// ELI15 chapter for EWC++ (Elastic Weight Consolidation) — P2.A.
//
// The reader has met trajectories (framing) and ReasoningBank (clustering).
// Now the question: "how do we learn from new sessions without forgetting
// what we learned in old ones?" That's what EWC++ handles.
export default {
  id: 'ewc',
  title: 'EWC++ — learning new tracks without forgetting old ones',
  oneLiner: 'A penalty term that pins "important" weights so fine-tuning on a new track doesn\'t clobber prior skills.',
  body: [
    '<p>Here\'s a problem neural networks have had since the 1990s, called',
    '<strong>catastrophic forgetting</strong>: train on task A, then train on',
    'task B, and the weights drift so much that the network forgets how to',
    'do task A. Humans don\'t do this (we can still ride a bike decades',
    'after learning guitar), but naive gradient descent does.</p>',
    '<p>For our racer that shows up like this: you train for a while on an',
    'oval, then draw a hairpin track. If the adapter just fine-tunes on the',
    'new track, it can forget everything it learned about ovals. Next time',
    'you load an oval, retrieval ranking has regressed.</p>',
    '<p><strong>EWC++</strong> (Elastic Weight Consolidation, improved',
    'variant) is the fix.</p>',
    '<h3 class="eli15-sub">The intuition: a spring on every weight</h3>',
    '<p>After training on task A, you compute for each weight a score: "how',
    'much did moving this weight change my loss?" High-score weights are the',
    'ones that mattered a lot for A — the "load-bearing" parameters. Low-',
    'score weights are the ones that could wiggle freely without hurting A\'s',
    'performance.</p>',
    '<p>Then when you train on task B, you add a penalty term to the loss:</p>',
    '<pre class="eli15-ascii">',
    '  loss  =  normal_loss_on_B  +  λ × Σ importance_i × (w_i - w_i_at_A)²',
    '                                 ^^^                  ^^^',
    '                                 per-weight           anchor: where the',
    '                                 "stiffness"          weight was after A',
    '</pre>',
    '<p>Translation: every weight has a little spring attaching it to where',
    'it was at the end of training A. Important weights have stiff springs',
    '(high <code>importance_i</code>), so gradient descent on B won\'t move',
    'them much. Unimportant weights have loose springs, so B can use them',
    'freely.</p>',
    '<h3 class="eli15-sub">The λ knob</h3>',
    '<p>The scalar multiplier <code>λ</code> (lambda) controls how seriously',
    'we take the springs overall. Our engine config sets',
    '<code>ewc_lambda: 1000</code>, which the SONA row in the panel displays',
    'as <code>λ 1000</code>. The <code>++</code> in EWC++ is about making the',
    'importance estimates online and cheap — the original EWC had to do an',
    'expensive Fisher-information sweep between tasks, which doesn\'t fit a',
    'real-time browser demo.</p>',
    '<h3 class="eli15-sub">Why it matters for our setup</h3>',
    '<p>Our archive is topology-scoped already — we don\'t want the',
    '<em>adapter</em> to silently erase what it learned about one family of',
    'tracks as you train on another. With EWC++ on, the SONA engine can keep',
    'nudging its internal parameters session-to-session without the panel\'s',
    '"Similar circuits" suddenly losing cluster quality on old tracks after',
    'you\'ve trained on new ones.</p>',
    '<p>If you\'ve ever seen a recommender system "unlearn" something useful',
    'after a big retraining pass, EWC-style regularisers are what production',
    'systems reach for to prevent it.</p>',
    '<h3 class="eli15-sub">What you can see in the panel</h3>',
    '<p>The SONA stats strip shows the current λ value. It\'s static (we set',
    'it at config time and don\'t anneal it), but seeing it there is the',
    '"yes, the regulariser is wired in" signal. The actual anti-forgetting',
    'happens inside the wasm agent during <code>forceLearn</code> and the',
    'background learning tick — you don\'t see it as a separate DOM widget,',
    'you see it as the ReasoningBank\'s cluster quality <em>not</em>',
    'degrading across sessions.</p>',
    '<h3 class="eli15-sub">Try it yourself (the hard version)</h3>',
    '<ul class="eli15-list">',
    '  <li>Train an oval to ~20 generations, leave phase 4. Note the patterns',
    '      (cluster count).</li>',
    '  <li>Draw and train a hairpin track to ~20 generations. Leave phase 4.</li>',
    '  <li>Reload the oval. "Similar circuits" should still show the oval',
    '      cluster with a healthy quality number — that\'s EWC++ doing its',
    '      job. Without it, the hairpin training would have overwritten the',
    '      oval cluster\'s centroid.</li>',
    '</ul>',
    '<p class="eli15-source">Source: the <code>@ruvector/sona</code> crate',
    '  (vendored under <code>vendor/ruvector/sona/</code>); our config sets',
    '  <code>ewc_lambda = 1000</code> in <code>AI-Car-Racer/sona/engine.js</code>.</p>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  after training on task A:',
    '        weights = w_A',
    '        importance_i = "how much did w_i matter for A?"',
    '',
    '  training on task B adds a penalty:',
    '        loss = loss_B  +  λ · Σ importance_i · (w_i − w_A_i)²',
    '                                               └── spring back to A ──┘',
    '',
    '  → important-for-A weights barely move, free weights adapt to B.',
    '</pre>',
  ].join('\n'),
  related: [
    'reasoningbank',
    'sona-trajectory',
    'lora',
  ],
};
