// eli15/chapters/gnn.js
// ELI15 chapter for the GNN reranker (shipped in P1.A).
//
// Target reading level: a curious 15-year-old who already read the framing
// chapter. We compare the GNN to the EMA reranker it replaces because most
// readers will have seen the EMA indicator in the Vector-Memory panel first.
export default {
  id: 'gnn',
  title: 'GNN reranker — like EMA, but with peer pressure',
  oneLiner: 'A tiny graph neural network that lets each archived brain\'s score be nudged by its parents\' scores.',
  body: [
    '<p>The <strong>EMA reranker</strong> gives every archived brain a "reputation" score that',
    'goes up when it was part of a good batch and down when it bombed. Each brain is judged on',
    'its own track record. That\'s fine for a few brains, but once the archive grows the',
    'scoring misses something obvious: <em>brains are related</em>. If the best brain in generation 12',
    'had five descendants in generations 13-17, their scores should talk to each other.</p>',
    '<p>The <strong>GNN reranker</strong> is exactly that. "GNN" = graph neural network. We take',
    'the archive, draw an arrow from every child brain to its parent(s) (using the <code>parentIds</code>',
    'we already record), and let a tiny neural network do one step of <em>message passing</em> along those',
    'arrows. A node\'s new score depends on its own stats <em>plus</em> what its neighbours were saying.',
    'Peer pressure, for brains.</p>',
    '<h3 class="eli15-sub">Message passing in three bullets</h3>',
    '<ul class="eli15-list">',
    '  <li><strong>Features.</strong> Every brain gets a tiny feature vector:',
    '    <code>[fitnessNorm, generationNorm, trackSim]</code>. Fitness on the track, how recent it is,',
    '    and how much its training track looked like the one you\'re on now.</li>',
    '  <li><strong>Messages.</strong> Every parent sends its feature vector to its children along the',
    '    lineage arrows. Each child collects those messages with an attention head — essentially a',
    '    weighted average where the weights are learned, not fixed.</li>',
    '  <li><strong>Update.</strong> The child mixes its own features with the aggregated messages and',
    '    produces a new embedding. We squash the mean of that vector into a multiplicative score',
    '    that slots into the same place the EMA score used to sit in <code>recommendSeeds()</code>.</li>',
    '</ul>',
    '<p>When the archive is small (&lt; 10 brains) the lineage graph is basically a chain of one or',
    'two nodes, so message passing has nothing useful to say and we <strong>fall back to EMA</strong>.',
    'You can see which mode is active right now in the Vector Memory panel — the "reranker:" row',
    'shows <code>gnn</code>, <code>ema</code>, or <code>none</code>.</p>',
    '<h3 class="eli15-sub">Try it yourself</h3>',
    '<ul class="eli15-list">',
    '  <li>Train a few generations on one track, then switch to a different track and train again.',
    '    Once the archive passes 10 brains the <strong>"reranker:" badge flips from <code>ema</code> to',
    '    <code>gnn</code></strong>. Hover the seeded-brains list and notice how seeds with rich lineage',
    '    (high parent-count "p" chip) now outrank equally-fit but isolated brains — that\'s the',
    '    peer-pressure signal in action.</li>',
    '</ul>',
    '<p class="eli15-source">Source: <code>AI-Car-Racer/gnnReranker.js</code> — the wasm graph layer;',
    '   <code>AI-Car-Racer/ruvectorBridge.js</code> — where <code>gnnScore</code> replaces <code>obsTerm</code>.</p>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  GENERATION  ARCHIVE GRAPH                SCORES FLOWING ALONG parentIds',
    '                                              (one message-pass step)',
    '',
    '    g0        A  (fit=120)                 A ──────────┐',
    '              │                             │          │',
    '    g1        B  (fit=135, parent=A)        ▼          │',
    '             ╱ ╲                            B  ←── parent score from A',
    '    g2      C   D  (parents=B)              │  ╲',
    '                                            ▼    ▼',
    '    g3      E  (parents=C,D)                C    D  ←── each gets B\'s message',
    '                                                    ╲',
    '                                                      ▼',
    '                                                      E  ←── sees both C and D',
    '',
    '  EMA:  E\'s score only cares about E\'s own observation history.',
    '  GNN:  E\'s score also absorbs C and D (who absorbed B, who absorbed A).',
    '        Good lineage = score bonus. Weak lineage = score penalty.',
    '</pre>',
  ].join('\n'),
  related: [
    'what-is-this-project',
  ],
};
