// eli15/chapters/hyperbolic-space.js
// Why trees fit better on a saddle than on a table.
export default {
  id: 'hyperbolic-space',
  title: 'Hyperbolic HNSW — why trees fit better on a saddle',
  oneLiner: 'Swap the flat-space neighbour graph for a Poincaré-ball one; trees embed with less distortion.',
  body: [
    '<p>Earlier chapters used <a href="#" data-eli15="vectordb-hnsw">HNSW</a> to find',
    'near-neighbours in a 512-dimensional flat space. "Flat" here means Euclidean:',
    'the distance between two vectors is the plain straight-line formula you learned',
    'in school. P3.A offers a second option — the same HNSW graph, but laid out in',
    '<strong>hyperbolic space</strong>.</p>',

    '<h3>Why bother?</h3>',
    '<p>Imagine trying to arrange a family tree on a flat sheet of paper. The root',
    'has a few kids; each of those has a few kids; each of <em>those</em> has a few',
    'kids. After five generations you need 243 slots along the same radius, and they',
    'start crowding each other. The geometry of a flat surface doesn\'t have enough',
    '"room" to grow exponentially — you either shrink the children so they fit, or',
    'let them overlap.</p>',
    '<p>A <strong>saddle-shaped</strong> surface (formally, one with negative curvature)',
    'has that room. Circumference grows exponentially with radius instead of linearly.',
    'So every branch of a tree gets its own breathable wedge, and distances between',
    'cousins reflect how many generations separate them — not how the artist happened',
    'to draw the page.</p>',

    '<h3>What actually changes in the code</h3>',
    '<p>When <code>?hhnsw=1</code> is set (or the A/B toggle strip flips <em>index</em>',
    'to <em>hyperbolic</em>), the bridge swaps the backing class for <code>_trackDB</code>,',
    '<code>_brainDB</code>, and <code>_dynamicsDB</code> from <code>VectorDB</code>',
    '(Euclidean) to a <code>HyperbolicVectorDB</code> wrapper around',
    '<code>ruvector-hyperbolic-hnsw-wasm</code>. Three things are different under the',
    'new backend:</p>',
    '<ul>',
    '  <li><strong>Projection.</strong> Our CNN track vectors have norm = 1, so they',
    '      live on the surface of a unit sphere. Hyperbolic HNSW wants them',
    '      <em>inside</em> the Poincaré ball (norm &lt; 1/√c). The adapter calls',
    '      <code>projectToBall</code> on every insert and query to shrink them a hair.</li>',
    '  <li><strong>Distance.</strong> Instead of cosine distance, neighbours are',
    '      scored by <em>Poincaré distance</em>, which blows up near the ball\'s',
    '      boundary (that\'s how "exponential room" happens mathematically).</li>',
    '  <li><strong>Score squash.</strong> Poincaré distance is unbounded, so the',
    '      adapter maps it through <code>1 − e^(−d)</code> to produce a [0, 1)',
    '      distance-lookalike. This keeps the bridge\'s multiplicative composition',
    '      (<code>trackTerm × fitTerm × rerankTerm</code>) in a sensible range and',
    '      preserves ranking — only absolute magnitudes shift.</li>',
    '</ul>',

    '<h3>Does it help <em>here</em>?</h3>',
    '<p>Honest answer from the bench: <strong>not on our current data.</strong>',
    '<code>tests/bench-hnsw.html</code> runs two scenarios so you can see why:</p>',
    '<ul>',
    '  <li><strong>Spherical</strong> (L2-normalised unit vectors — what our',
    '      CnnEmbedder actually produces): Euclidean recall@5 ≈ 100%, hyperbolic',
    '      recall@5 ≈ 85%. A clear loss.</li>',
    '  <li><strong>Ball-native</strong> (same cluster structure but random radii',
    '      inside the ball — what hyperbolic HNSW was designed for): Euclidean',
    '      ≈ 100%, hyperbolic ≈ 99.8%. Near-tie.</li>',
    '</ul>',
    '<p>The ~15 percentage-point gap disappears when we stop feeding the index',
    'vectors that all sit on the ball\'s boundary. That\'s strong evidence the',
    'index is <em>correct</em>, it\'s just the wrong tool for sphere-shaped data.',
    'Interestingly, hyperbolic also has lower p99 latency in our bench (smaller',
    'search budget to reach a decision) — it\'s not paying a speed cost, just a',
    'recall cost when the manifold doesn\'t fit.</p>',
    '<p>So why keep the toggle? Because the <em>lineage</em> DAG (P3.B) is very',
    'much tree-shaped, and the <em>dynamics</em> key (P1.C) could carry',
    'radial/magnitude information that matters. When those archives grow large',
    'enough to separate hyperbolic\'s wins from spherical\'s losses, the toggle is',
    'already in place to exploit it. Default stays Euclidean; hyperbolic is',
    'opt-in, and this chapter exists so the trade-off is visible rather than',
    'hidden.</p>',

    '<h3>Try it yourself</h3>',
    '<ul>',
    '  <li>Open the A/B toggle strip in the Vector Memory panel and flip <em>index</em>',
    '      from <em>euclidean</em> to <em>hyperbolic</em>. Watch <code>window.__rvBridge.info().policy.index</code>',
    '      change; run a generation and notice whether the seed ordering shifts.</li>',
    '  <li>Load <code>tests/bench-hnsw.html</code> from a local http server. Two',
    '      scenarios, same HNSW under the hood: spherical (our actual workload,',
    '      hyperbolic loses ~15 pp on recall) and ball-native (hyperbolic matches',
    '      Euclidean). Compare the tables side-by-side — that\'s the manifold',
    '      mismatch rendered as numbers.</li>',
    '  <li>Add <code>?hhnsw=1</code> to the URL to boot with hyperbolic already',
    '      selected, so the panel doesn\'t flicker between modes during warm-up.</li>',
    '</ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  Euclidean embedding of a deep tree        Hyperbolic (Poincaré) embedding',
    '  — children crowd their parent             — circumference grows exponentially',
    '                                            with radius; every branch has room',
    '',
    '          A                                        A',
    '        / | \\                                    ╱   ╲',
    '       B  C  D                                  B     C',
    '     / |\\ |\\ |\\                                ╱╲   ╱╲',
    '    E F G H I J K                              E  F G  H',
    '    (grandkids overlap)                        (spread around the disc edge)',
    '',
    '  Key: in the Poincaré disc, "infinity" is the boundary circle. Distances',
    '  near the boundary blow up, which is exactly the room a tree needs.',
    '</pre>',
  ].join('\n'),
  related: [
    'vectordb-hnsw',
    'lineage-dag',
    'cnn-embedder',
  ],
};
