// eli15/chapters/hyperbolic-space.js
// Why trees fit better on a saddle than on a table.
export default {
  id: 'hyperbolic-space',
  title: 'Hyperbolic HNSW — why trees fit better on a saddle',
  oneLiner: 'Swap the flat-space neighbour graph for a Poincaré-ball one; trees embed with less distortion.',
  body: [
    '<p>Earlier chapters used <a href="#" data-eli15="vectordb-hnsw">HNSW</a> to find',
    'near-neighbours in a 512-dimensional flat space. "Flat" here means Euclidean:',
    'the distance between two vectors is the plain straight-line formula you learned',
    'in school. P3.A offers a second option — the same HNSW graph, but laid out in',
    '<strong>hyperbolic space</strong>.</p>',

    '<h3>Why bother?</h3>',
    '<p>Imagine trying to arrange a family tree on a flat sheet of paper. The root',
    'has a few kids; each of those has a few kids; each of <em>those</em> has a few',
    'kids. After five generations you need 243 slots along the same radius, and they',
    'start crowding each other. The geometry of a flat surface doesn\'t have enough',
    '"room" to grow exponentially — you either shrink the children so they fit, or',
    'let them overlap.</p>',
    '<p>A <strong>saddle-shaped</strong> surface (formally, one with negative curvature)',
    'has that room. Circumference grows exponentially with radius instead of linearly.',
    'So every branch of a tree gets its own breathable wedge, and distances between',
    'cousins reflect how many generations separate them — not how the artist happened',
    'to draw the page.</p>',

    '<h3>What actually changes in the code</h3>',
    '<p>When <code>?hhnsw=1</code> is set (or the A/B toggle strip flips <em>index</em>',
    'to <em>hyperbolic</em>), the bridge swaps the backing class for <code>_trackDB</code>,',
    '<code>_brainDB</code>, and <code>_dynamicsDB</code> from <code>VectorDB</code>',
    '(Euclidean) to a <code>HyperbolicVectorDB</code> wrapper around',
    '<code>ruvector-hyperbolic-hnsw-wasm</code>. Three things are different under the',
    'new backend:</p>',
    '<ul>',
    '  <li><strong>Projection.</strong> Our CNN track vectors have norm = 1, so they',
    '      live on the surface of a unit sphere. Hyperbolic HNSW wants them',
    '      <em>inside</em> the Poincaré ball (norm &lt; 1/√c). The adapter calls',
    '      <code>projectToBall</code> on every insert and query to shrink them a hair.</li>',
    '  <li><strong>Distance.</strong> Instead of cosine distance, neighbours are',
    '      scored by <em>Poincaré distance</em>, which blows up near the ball\'s',
    '      boundary (that\'s how "exponential room" happens mathematically).</li>',
    '  <li><strong>Score squash.</strong> Poincaré distance is unbounded, so the',
    '      adapter maps it through <code>1 − e^(−d)</code> to produce a [0, 1)',
    '      distance-lookalike. This keeps the bridge\'s multiplicative composition',
    '      (<code>trackTerm × fitTerm × rerankTerm</code>) in a sensible range and',
    '      preserves ranking — only absolute magnitudes shift.</li>',
    '</ul>',

    '<h3>Does it help <em>here</em>?</h3>',
    '<p>Maybe! It depends on whether our archived data actually has tree-like',
    'structure. The lineage DAG (P3.B) very much does — brains have parents,',
    'grand-parents, and cousins. Track embeddings from the CNN are less clearly',
    'hierarchical; they live on a sphere, which flat HNSW handles fine.</p>',
    '<p>That\'s why P3.A ships the toggle <em>and</em> a benchmark harness at',
    '<code>tests/bench-hnsw.html</code>. Flip both indices over the same saved',
    'archive, measure recall@5 and p99 latency, and let the numbers decide. The',
    'confidence gate for this phase is "don\'t regress" — recall@5 ≥ Euclidean',
    'baseline and p99 within 1.5× — not "hyperbolic wins by a mile".</p>',

    '<h3>Try it yourself</h3>',
    '<ul>',
    '  <li>Open the A/B toggle strip in the Vector Memory panel and flip <em>index</em>',
    '      from <em>euclidean</em> to <em>hyperbolic</em>. Watch <code>window.__rvBridge.info().policy.index</code>',
    '      change; run a generation and notice whether the seed ordering shifts.</li>',
    '  <li>Load <code>tests/bench-hnsw.html</code> from a local http server. It runs',
    '      100 random queries under both indices and prints recall@5 + p99 latency.</li>',
    '  <li>Add <code>?hhnsw=1</code> to the URL to boot with hyperbolic already',
    '      selected, so the panel doesn\'t flicker between modes during warm-up.</li>',
    '</ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  Euclidean embedding of a deep tree        Hyperbolic (Poincaré) embedding',
    '  — children crowd their parent             — circumference grows exponentially',
    '                                            with radius; every branch has room',
    '',
    '          A                                        A',
    '        / | \\                                    ╱   ╲',
    '       B  C  D                                  B     C',
    '     / |\\ |\\ |\\                                ╱╲   ╱╲',
    '    E F G H I J K                              E  F G  H',
    '    (grandkids overlap)                        (spread around the disc edge)',
    '',
    '  Key: in the Poincaré disc, "infinity" is the boundary circle. Distances',
    '  near the boundary blow up, which is exactly the room a tree needs.',
    '</pre>',
  ].join('\n'),
  related: [
    'vectordb-hnsw',
    'lineage-dag',
    'cnn-embedder',
  ],
};
