// eli15/chapters/lineage-dag.js
// A DAG is a family tree where you can have two parents but never a time-loop.
export default {
  id: 'lineage-dag',
  title: 'A DAG — a family tree where you can\'t go back in time',
  oneLiner: 'Arrows always point "child → parent never exists"; there\'s no way to loop back to an ancestor.',
  body: [
    '<p>The earlier <a href="#" data-eli15="lineage">Lineage chapter</a> showed how every',
    'archived brain remembers its <code>parentIds</code>. Until now we walked that list by',
    'hand every time someone asked "where does this brain come from?" — a little piece of',
    'traversal code buried inside <code>getLineage()</code>. That works, but it means the',
    'same graph gets re-derived for every question. As the archive grows, that adds up.</p>',
    '<p>P3.B promotes the family tree to a proper <strong>DAG</strong>: a',
    '<em>Directed Acyclic Graph</em>. Three words, one per letter:</p>',
    '<ul>',
    '  <li><strong>Directed</strong> — each edge points one way. We use',
    '      <code>parent → child</code>. You can\'t walk backwards along an edge.</li>',
    '  <li><strong>Acyclic</strong> — no cycles. You can never start at a brain, follow',
    '      arrows, and end up back where you started. In this project the constraint is',
    '      automatic: a child is archived <em>after</em> its parents, so an edge from a newer',
    '      brain to an older one would be a time-loop.</li>',
    '  <li><strong>Graph</strong> — nodes + edges. Unlike a tree, a single node can have',
    '      multiple parents (when the GA seeds a batch from two retrieved brains, the child',
    '      has two entries in <code>parentIds</code>).</li>',
    '</ul>',
    '<p>The structure lives in <code>vendor/ruvector/ruvector_dag_wasm</code> — a tiny Rust',
    'crate that stores nodes as <code>(id, op, cost)</code> and edges as <code>(from, to)</code>,',
    'and <em>rejects any edge that would create a cycle</em>. We shadow it on the JS side',
    'with a <code>childToParents</code> map so <code>getLineage()</code> can still answer in',
    'O(depth) without touching wasm at all for the hot-path walk.</p>',
    '<p>Why bother promoting it, then? Two reasons.</p>',
    '<ul>',
    '  <li><strong>Viewer.</strong> The new "🌳 Lineage" panel renders the whole DAG as a',
    '      scatter of dots — y-axis is <em>generation</em>, colour is <em>fitness</em>. Lines',
    '      connect each parent to its child. You can see, at a glance, which ancestral spine',
    '      produced your current best brains.</li>',
    '  <li><strong>Invariants.</strong> The Rust side\'s cycle check fires a warning if data',
    '      corruption ever produces a malformed <code>parentIds</code>. Before this phase we',
    '      just silently traversed junk.</li>',
    '</ul>',
    '<h3>Try it yourself</h3>',
    '<ul>',
    '  <li>Train through a few generations in Phase 4, then open the 🌳 Lineage panel. Drag',
    '      your eye from the top (gen 0) to the bottom; every brain you see was a retrieved',
    '      seed at some point, and every edge is one parent → one child.</li>',
    '  <li>In DevTools: <code>window.__rvBridge.getLineageGraph()</code> returns the same',
    '      snapshot the viewer uses. Count nodes and edges — edge count should be ≤ 2×',
    '      nodeCount (the GA caps <code>parentIds.length</code> at 2).</li>',
    '</ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '   Tree (one parent each)           DAG (may have two parents)',
    '',
    '        A                                A     X',
    '       / \\                                \\   /',
    '      B   C                                 B       ← B has parents A, X',
    '     / \\                                   / \\',
    '    D   E                                 D   E',
    '',
    '   Not allowed (cycle):',
    '        A',
    '         ↘',
    '          B',
    '         ↙',
    '        A   ← ruvector_dag_wasm rejects this edge at add_edge()',
    '</pre>',
  ].join('\n'),
  related: [
    'lineage',
    'genetic-algorithm',
    'gnn',
  ],
};
