// eli15/chapters/lora.js
// ELI15 chapter for the MicroLoRA track-vector adapter (P1.B).
//
// The reader has met the CNN embedder (turns a track image into 512 numbers)
// and the HNSW index (finds nearby vectors fast). This chapter explains the
// thin layer of *learning* we slip between the two, and why "small matrix
// instead of retraining the big one" is the whole trick.
export default {
  id: 'lora',
  title: 'LoRA — a tiny matrix that bends the embedding',
  oneLiner: 'Two skinny matrices learn to nudge the 512-number track vector toward arrangements that retrieve good seeds.',
  body: [
    '<p>The CNN that turns a track picture into 512 numbers is <strong>frozen</strong>. We never',
    'retrain it. That\'s deliberate — retraining the CNN would require collecting thousands of',
    'labelled track examples and shipping a multi-megabyte model update. Cheap on a research',
    'cluster, ridiculous in a browser tab.</p>',
    '<p>But the frozen embedding has a problem: <em>it doesn\'t know what you care about</em>. Two',
    'tracks might look visually identical to the CNN (similar curve density, similar overall shape)',
    'while one of them is a graveyard for our genetic-algorithm cars and the other is a cake-walk.',
    'The CNN was never told that a "good" embedding clusters tracks by <em>how the GA does on them</em>,',
    'because it was trained on completely unrelated images.</p>',
    '<p><strong>LoRA</strong> — Low-Rank Adaptation — is the fix. Instead of editing the CNN, we leave',
    'it alone and add a tiny correction <em>after</em> it:</p>',
    '<pre class="eli15-ascii">',
    '  trackVec_adapted  =  trackVec  +  alpha · (trackVec @ A @ B)',
    '                      └────┬────┘   └─────────┬──────────┘',
    '                       512 numbers           a small bend',
    '</pre>',
    '<p>A and B are skinny matrices. <code>A</code> is 512×2 (squashes the embedding down to 2 numbers).',
    '<code>B</code> is 2×512 (expands those 2 numbers back to 512). The product <code>A @ B</code> is a',
    '512×512 matrix, but its <em>rank</em> — the number of independent directions it can move things in —',
    'is at most 2. We can only push the embedding in two directions, not in all 512 of them.',
    '"Why two?" Because the GA only gives us one bit of information per generation ("this run was',
    'better / worse than the running average"); learning anything richer would just memorise noise.</p>',
    '<h3 class="eli15-sub">Why a small matrix instead of retraining the big one</h3>',
    '<ul class="eli15-list">',
    '  <li><strong>Cheap.</strong> Two skinny matrices = ~2,000 weights per half. The CNN has tens of',
    '    millions. Updating the small thing is microseconds; updating the big thing would be seconds.</li>',
    '  <li><strong>Reversible.</strong> If the adaptation goes wrong (the GA gets unlucky early on and',
    '    teaches the adapter the wrong lesson), we just zero out B. The CNN is untouched.</li>',
    '  <li><strong>Stable.</strong> Most of what the CNN already knows about images is correct — edges,',
    '    curves, blobs. We only want to nudge the parts that matter for our task.</li>',
    '</ul>',
    '<h3 class="eli15-sub">How the update happens</h3>',
    '<p>Every time we archive a brain (end of a generation), the bridge calls',
    '<code>trackAdapter.reward(fitness)</code>. The adapter holds an EMA "baseline" — a running guess at',
    '"this is roughly how good this track usually is". If the just-finished generation came in',
    '<em>above</em> baseline, the adapter takes a small step in B that strengthens whatever the current',
    'track vector pointed at. If the generation was below baseline, no update — we don\'t want the',
    'adapter to learn from bad runs (this matches what the underlying Rust crate does).</p>',
    '<h3 class="eli15-sub">Why two halves under the hood</h3>',
    '<p>The upstream <code>WasmMicroLoRA</code> crate hard-codes its B matrix at 256 columns wide.',
    'Our track vectors are 512 numbers. So <code>trackAdapter.js</code> wires up <strong>two</strong>',
    'WasmMicroLoRA(256) instances — one for the lower 256 numbers, one for the upper. From outside it',
    'still looks like one 512-in / 512-out function. The adaptation is "block-diagonal rank-2" (rank-2',
    'on each half independently) instead of rank-2 across the whole vector — slightly less',
    'expressive, but it lets us reuse the published library without forking it.</p>',
    '<h3 class="eli15-sub">Try it yourself</h3>',
    '<ul class="eli15-list">',
    '  <li>Open the Vector-Memory panel and look at the <strong>"track adapter:"</strong> row. The',
    '    <em>drift</em> number is the L2 distance between the raw embedding and the adapted one. On a',
    '    fresh archive (or right after <code>_debugReset()</code>) it starts near zero. Train through a',
    '    few generations on the same track and watch the sparkline rise as B accumulates updates.</li>',
    '  <li>Add <code>?rv=0</code> to the URL. The whole bridge — including the adapter — silently',
    '    short-circuits, so you can compare A/B against the no-adapter baseline.</li>',
    '</ul>',
    '<p class="eli15-source">Source: <code>AI-Car-Racer/lora/trackAdapter.js</code> — the wrapper;',
    '   <code>vendor/ruvector/ruvector_learning_wasm/</code> — the wasm engine;',
    '   <code>AI-Car-Racer/ruvectorBridge.js</code> — the integration points (recommendSeeds + archiveBrain).</p>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  THE FROZEN CNN                THE LoRA ADAPTER (the part that learns)',
    '',
    '  ┌─────────────────┐           ┌──────┐    ┌───────────┐',
    '  │  raw track png  │──CNN─►512 │  A   │ 2  │     B     │ 512',
    '  │  (224×224 px)   │   never   │512×2 │───►│   2×512   │────► adapted',
    '  └─────────────────┘  changes  └──────┘    └───────────┘      track vec',
    '                                  (held)    (zero at start;',
    '                                            grows with reward)',
    '',
    '   adapted = raw + alpha · (raw @ A @ B)',
    '   "alpha" keeps the bend small at first; "rank 2" keeps it cheap.',
    '</pre>',
  ].join('\n'),
  related: [
    'cnn-embedder',
    'vectordb-hnsw',
    'track-similarity',
  ],
};
