// eli15/chapters/quantization.js
// Phase 1B (F1) — real content. Explains the RaBitQ + Hadamard 1-bit
// quantizer that ships in AI-Car-Racer/quantization/. Also flags the
// scope boundary: this is a Euclidean/cosine trick — the hyperbolic
// HNSW path is deliberately out of scope.
export default {
  id: 'quantization',
  title: 'Throwing away 31 out of every 32 bits and still finding the right neighbour',
  oneLiner: 'A brain\'s fingerprint is hundreds of decimal numbers. RaBitQ keeps only the sign bit of each and barely loses any accuracy.',
  body: [
    '<p>Every brain gets flattened into a vector of <strong>244 floating-point',
    'numbers</strong> (see <code>brainCodec.js</code>: 10·16 + 16 biases, 16·4 + 4',
    'outputs). A <code>float32</code> is four bytes, so one brain is ~976 bytes and',
    'an archive of 5,000 brains is ~5 MB of RAM. All of that, just to answer',
    '"which past brain is most similar to this new one?"</p>',

    '<h3>SimHash, but for brains</h3>',
    '<p>Here\'s the cheap trick. If two vectors point in similar directions,',
    'a <em>random hyperplane</em> through the origin will land them on the same',
    'side most of the time. Each hyperplane gives you one bit — 1 if the vector',
    'is on one side, 0 if the other. Take many hyperplanes and the <strong>count',
    'of disagreeing bits</strong> (Hamming distance) between two vectors\'',
    'bit-strings is proportional to the angle between them. That\'s <strong>SimHash</strong>,',
    'and it\'s the same idea as <strong>RaBitQ</strong> with one upgrade: instead of',
    'picking random hyperplanes, we use the axes of a <strong>Hadamard rotation</strong>.</p>',

    '<h3>Why Hadamard instead of random</h3>',
    '<p>A <strong>Fast Walsh-Hadamard Transform</strong> rotates the vector with',
    'a matrix full of ±1s. It\'s orthonormal (preserves inner products),',
    'data-independent (no training, no codebook), and runs in',
    '<code>O(D log D)</code>. After the rotation, each axis carries roughly the',
    'same amount of information — which is exactly what makes the sign-bit',
    'trick work well. The rotation happens in place on a vector padded to',
    'the next power of two (for us: 244 → 256).</p>',

    '<pre class="eli15-ascii">',
    '  raw 244-d float  ─►  zero-pad to 256  ─►  Hadamard rotate',
    '       976 B                                (spreads energy)',
    '                                                 │',
    '                                                 ▼',
    '  pack 256 sign bits into 8× Uint32  ◄──  take sign of each axis',
    '       32 B  (+ 64 B float residual for rerank)',
    '',
    '  distance(a, b)  = popcount(a XOR b)      ─►  Hamming distance',
    '  cos(angle)      ≈ cos(π · H / 256)       ─►  recovered cosine',
    '</pre>',

    '<h3>The 32× memory win</h3>',
    '<p>Replacing 32 bits with 1 is, by definition, a 32× compression. In',
    'practice we also keep a small <strong>float residual</strong> (16 floats =',
    '64 bytes) so a rerank pass can break ties among Hamming-equidistant',
    'candidates. The total is 96 bytes vs. 976 — a ~10× overall shrink with',
    'the residual, 30× for the bit-code alone. On a 5,000-brain archive that\'s',
    '~5 MB → ~500 KB.</p>',

    '<h3>How much accuracy we lose</h3>',
    '<p>The pure-JS implementation in <code>quantization/rabitq.js</code> hits',
    '<strong>recall@10 ≥ 0.9</strong> against the float baseline on synthetic',
    'brain-lineage workloads (100 vectors clustered around 10 parents, matching',
    'how real GA archives grow by mutation). The viewer in',
    '<code>quantization/viewer.js</code> shows this live: a scatter plot of',
    '<em>true cosine</em> vs. <em>estimated cosine</em> clusters tightly along',
    'the y=x diagonal. You can verify it yourself with',
    '<code>tests/quantization-recall.html</code> — open it and read the number.</p>',

    '<h3>What this is NOT for</h3>',
    '<p><strong>Hyperbolic HNSW is explicitly out of scope for F1.</strong> The',
    'sign-bit-as-angle argument relies on Euclidean geometry — the rotation',
    'is orthonormal in ℝⁿ, and the Hamming/π identity recovers an Euclidean',
    'angle. Hyperbolic space curves, angles mean something different, and a',
    'naive sign-bit quantizer would silently distort distances. If we ever',
    'want a quantized hyperbolic path (not on the roadmap as of this writing),',
    'it needs a separate derivation — probably a Poincaré-disk projection',
    'before rotation. For now: <code>?quant=1</code> only affects the',
    'Euclidean <code>VectorDB</code>; the hyperbolic adapter is untouched.</p>',

    '<h3>Try it yourself</h3>',
    '<ul>',
    '<li>Open <code>tests/quantization-recall.html</code> to see recall@10',
    'printed as a number.</li>',
    '<li>Read <code>AI-Car-Racer/quantization/index.js</code> for the public API:',
    '<code>quantize(flat)</code>, <code>hammingDistance(a, b)</code>,',
    '<code>estimatedCosine(a, b)</code>.</li>',
    '<li>The integration slot lives in <code>ruvectorBridge.js</code> under',
    '<code>setConsistencyMode</code>\'s sibling (Phase 2A wires it up).</li>',
    '</ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  angle between vectors  ─────────────────────────────────────►',
    '       0°                  45°                  90°',
    '   same direction    half of bits agree    uncorrelated',
    '       │                     │                     │',
    '   Hamming = 0         Hamming = 64          Hamming = 128',
    '  (0/256 disagree)   (64/256 disagree)    (128/256 disagree)',
    '',
    '  Estimated cosine = cos(π · Hamming / 256)',
    '</pre>',
  ].join('\n'),
  related: [
    'vectordb-hnsw',
    'federation',
  ],
};
