// eli15/chapters/reasoningbank.js
// ELI15 chapter for the SONA ReasoningBank (P2.A).
//
// Reader has met trajectories (the tape) and is now asking: "OK, what
// does SONA actually DO with all those tapes?" Answer: it clusters them.
export default {
  id: 'reasoningbank',
  title: 'ReasoningBank — clusters of "situations that looked alike"',
  oneLiner: 'k-means over trajectory embeddings turns many sessions of driving into a handful of reusable patterns.',
  body: [
    '<p>Imagine a driving instructor who\'s taught a thousand students. After',
    'a while, she doesn\'t think of each student individually — she thinks in',
    'terms of <strong>types</strong>. "Oh, this one is a jerky-steering,',
    'late-braker type." Or: "this track is one of those pinch-point-then-',
    'hairpin types." The instructor\'s brain has quietly clustered its',
    'experience into a small number of recognisable categories.</p>',
    '<p>The ReasoningBank is SONA\'s version of that.</p>',
    '<h3 class="eli15-sub">From a pile of vectors to a handful of clusters</h3>',
    '<p>Every <code>addStep</code> + <code>endTrajectory</code> ships a bunch',
    'of (embedding, reward) pairs into the wasm agent. These accumulate in a',
    'trajectory buffer until there are enough to learn from — then SONA runs',
    '<strong>k-means clustering</strong> to find groups of embeddings that',
    'look alike.</p>',
    '<pre class="eli15-ascii">',
    '  trajectory steps (hundreds)              ReasoningBank patterns (≤16)',
    '',
    '  • jerky-steering fast-speed  ┐',
    '  • jerky-steering fast-speed  ├──►  pattern A  (12 members, avg q=0.43)',
    '  • jerky-steering fast-speed  ┘',
    '',
    '  • smooth slow                ┐',
    '  • smooth slow                ├──►  pattern B  (8 members, avg q=0.71)',
    '  • smooth slow                ┘',
    '',
    '  • stuck-against-wall         ──►  pattern C  (3 members, avg q=0.05)',
    '</pre>',
    '<p>Each <strong>pattern</strong> has a centroid (the average embedding of',
    'its members), a member count, and an average reward. In the side panel\'s',
    '"Similar circuits" sub-panel, that\'s exactly what you see: for each of',
    'the top-5 patterns closest to the current track, a cosine-similarity %,',
    'a member count, and a quality average.</p>',
    '<h3 class="eli15-sub">Why k-means and not something fancier?</h3>',
    '<p>k-means is cheap, deterministic, and interpretable. Upstream SONA',
    'config caps us at 16 clusters; that\'s plenty for the handful of distinct',
    '"situation types" a racer is likely to encounter. Going fancier (e.g.',
    'HDBSCAN) would add wasm binary size with no discernible win at this',
    'scale.</p>',
    '<h3 class="eli15-sub">"Similar circuits" — how the panel reads this</h3>',
    '<p>When you\'re on a track, the panel asks SONA: "of your current',
    'clusters, which ones look most like this track vector?" The top-5 come',
    'back sorted by cosine similarity. High-quality clusters (big avg-q) with',
    'many members are the pattern SONA is most confident about; a low-member',
    'cluster with medium quality is a "I\'ve seen this once or twice, maybe"',
    'pattern.</p>',
    '<p>The plan calls this surface out specifically because it closes the',
    'loop on ELI15: you can watch the agent <em>organise its experience</em>',
    'into named categories instead of treating the archive as a black box.</p>',
    '<h3 class="eli15-sub">Why quality_threshold matters</h3>',
    '<p>SONA refuses to cluster trajectories below a quality threshold, on',
    'the theory that garbage input = garbage clusters. Our engine sets this',
    'to <code>0.15</code> (below the default 0.3) because our normalised',
    'fitness can sit low early in training — a higher threshold would keep',
    'the ReasoningBank empty until generation 20+, which is too late for the',
    '20-generation demo gate.</p>',
    '<h3 class="eli15-sub">Try it yourself</h3>',
    '<ul class="eli15-list">',
    '  <li>Train ~20 generations on one track. Leave phase 4. The SONA row\'s',
    '      <code>patterns</code> counter should read ≥1. Every session you',
    '      close adds a ReasoningBank learning tick.</li>',
    '  <li>Draw a second, different track. Enter phase 4. The "Similar',
    '      circuits" sub-panel should populate with rows — these are the',
    '      patterns SONA learned from the first session, now ranked by',
    '      cosine to the new track.</li>',
    '  <li>Patterns with a high quality average and ≥3 members are the ones',
    '      SONA would currently consider "trustworthy advice".</li>',
    '</ul>',
    '<p class="eli15-source">Source: <code>AI-Car-Racer/sona/engine.js</code>',
    '  — <code>findPatterns()</code> and <code>readPatternCount()</code>;',
    '  upstream logic lives in the <code>@ruvector/sona</code> crate under',
    '  <code>vendor/ruvector/sona/</code>.</p>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  many trajectory steps              k-means                patterns (≤16)',
    '     (hundreds of vectors)      ──────────────────►     (centroid + members',
    '                                  on forceLearn              + avg quality)',
    '                                  or background tick)',
    '</pre>',
  ].join('\n'),
  related: [
    'sona-trajectory',
    'ewc',
    'dynamics-embedding',
  ],
};
