// eli15/chapters/vectordb-hnsw.js
// Why nearest-neighbour search across hundreds of 512-d vectors is fast.
export default {
  id: 'vectordb-hnsw',
  title: 'Nearest-neighbour search that doesn\'t scan everything',
  oneLiner: 'HNSW builds a multi-layer graph so queries only touch log(N) vectors.',
  body: [
    '<p>Once every track you\'ve finished turns into a 512-dim vector (see',
    '<code>cnn-embedder</code>), you end up with an <strong>archive</strong>: maybe 50, maybe 500,',
    'maybe 5,000 track vectors plus just as many brain vectors. When a new track shows up,',
    'we want the <em>k</em> most similar past tracks so we can warm-start training from their',
    'brains. That\'s a <strong>nearest-neighbour (NN) search</strong>.</p>',
    '<p>The dumb way is linear scan: cosine-compare the new vector against all <em>N</em> entries.',
    'That\'s fine for N=50 but gets slow fast. Instead we use a <strong>VectorDB</strong> built on',
    'top of <strong>HNSW</strong> — Hierarchical Navigable Small World graphs. Look at',
    '<code>ruvectorBridge.js:46-48</code>:</p>',
    '<pre class="eli15-ascii">',
    '_brainDB = new VectorDB(FLAT_LENGTH, \'cosine\');   // 92-d brain weights',
    '_trackDB = new VectorDB(TRACK_DIM, \'cosine\');     // 512-d track embeddings',
    '_cnn     = new CnnEmbedder();',
    '</pre>',
    '<p>HNSW builds a <em>layered graph</em> over the vectors. The top layer is sparse — think',
    '"motorways": a few nodes with long-distance links. Each layer below has more nodes and',
    'shorter links, down to the bottom layer which has every single vector. A query starts',
    'at the top, hops greedily toward vectors close to the query, then drops down a layer',
    'and refines. The result: finding the 10 nearest neighbours in a 10,000-vector archive',
    'touches maybe 50 vectors instead of all 10,000.</p>',
    '<p>The HNSW library is written in Rust and compiled to <code>.wasm</code>. That\'s why',
    'you see <code>vendor/ruvector/ruvector_wasm/</code> in the repo — pre-built binaries so',
    'users don\'t need a Rust toolchain.</p>',
    '<h3>Try it yourself</h3>',
    '<ul><li>Open the <strong>Vector Memory</strong> panel (bottom-right during phase 4). The',
    '"N brains · M tracks · K obs" readout is live from <code>VectorDB.info()</code>. Train',
    'through several tracks and watch both counters grow — each new track adds one',
    '<code>tracks</code> and one <code>brains</code> entry to HNSW.</li></ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  HNSW layers    "motorways"',
    '  layer 2   ●─────────────●─────────●          (sparse)',
    '            │             │',
    '  layer 1   ●──●─────●────●──●───●──●          (medium)',
    '            │  │     │    │  │   │  │',
    '  layer 0   ●●●●●●●●●●●●●●●●●●●●●●●●●●         (all vectors)',
    '',
    '  query q :  start at layer 2, greedily hop toward q.',
    '             drop a layer, refine.  drop a layer, refine.',
    '             touches ~ log(N) vectors, not all N.',
    '</pre>',
  ].join('\n'),
  related: [
    'cnn-embedder',
    'track-similarity',
    'ema-reranker',
  ],
};
