// eli15/chapters/warm-restart.js
// Phase 1A (F3) — whole-archive export/import (warm-restart bundles).
export default {
  id: 'warm-restart',
  title: 'Saving and reopening the whole brain archive',
  oneLiner: 'A brain archive is a museum — you can save it, reopen it tomorrow, or give the whole museum to a friend.',
  body: [
    '<p>Imagine every generation you train drops off another brain at a',
    'museum. After a while the museum has hundreds of brains — each one a',
    'tiny record of what worked on which track. That museum is <em>this',
    'app\'s archive</em>. It\'s how a later generation can warm-start from a',
    'cousin that already learned a similar corner, instead of relearning',
    'from scratch.</p>',

    '<p>Up to now the museum only lived inside your browser. The moment you',
    'opened an incognito tab, or cleared site data, or opened the page on',
    'a friend\'s laptop, the museum was empty again. <strong>Warm-restart',
    'bundles</strong> fix that. You can download the entire museum as a',
    'single file, re-open it on another day, or email it to someone else',
    'so their browser starts with your pre-trained population.</p>',

    '<h3>What\'s actually in the file?</h3>',
    '<p>Three things:</p>',
    '<ul>',
    '  <li>Every archived brain\'s <strong>flat weight vector</strong> (the',
    '    244 numbers that define that neural net) plus its metadata —',
    '    fitness, generation, parents, which track it trained on.</li>',
    '  <li>Every unique <strong>track fingerprint</strong> the archive has',
    '    seen (the 512-dim CNN embedding of the track shape), so the',
    '    retrieval system can match "is the current track like anything we',
    '    have?" on the other side.</li>',
    '  <li>Every archived <strong>driving-dynamics vector</strong> — how',
    '    a brain actually drove during its run, not just what track it was',
    '    on. These are the tiebreakers for retrieval.</li>',
    '</ul>',

    '<h3>Replay vs. native-serialization</h3>',
    '<p>There are two ways to save a vector index to disk. The',
    '<strong>native</strong> way is to dump the HNSW graph\'s internal',
    'pointers and re-mount them on import — fast, but it requires the',
    'underlying wasm library to expose a serialize hook. Ours doesn\'t yet',
    '(it\'s an upstream patch we haven\'t merged). So we do the other',
    'thing: we write down the <strong>insertion order</strong> of every',
    'brain, and on import we <em>replay</em> the inserts in that exact',
    'order. HNSW is deterministic-ish when the order is fixed, so the',
    'rebuilt graph answers the same questions for the same queries. It\'s',
    'slower than a native restore on huge archives — a few hundred',
    'milliseconds for thousands of brains — but it\'s correct today, with',
    'no wasm patch required.</p>',

    '<p>The bundle is written as gzip\'d JSON with a short magic header',
    '(<code>VVARCHIVE v1 gzip</code>) so a truncated download fails loudly',
    'at import instead of silently loading half a museum. On browsers that',
    'lack the <code>CompressionStream</code> API, the bundle falls back to',
    'plain JSON — the magic header says which. There\'s also a',
    '<em>witness</em> field: a content hash of the rest of the file. If',
    'the hash doesn\'t match on import, the file got corrupted in transit',
    'and the importer bails before it touches your live archive.</p>',

    '<h3>How to use it</h3>',
    '<p>Warm-restart is hidden behind a URL flag while it bakes — visit',
    'this page with <code>?snapshots=1</code> appended (e.g.',
    '<code>…/index.html?snapshots=1</code>) and two new buttons will',
    'appear in the training panel: <strong>📦 Export archive</strong> (saves',
    'a <code>.vvarchive.json.gz</code> file to your Downloads folder) and',
    '<strong>📥 Import archive</strong> (reads one back in). Without the',
    'flag, the app behaves exactly as before — no new buttons, no new',
    'behaviour.</p>',

    '<p>Try it: train one generation, click Export. Clear the archive from',
    'the console (<code>await window.__rvBridge._debugReset()</code>),',
    'reload the page with <code>?snapshots=1</code>, click Import, pick',
    'the file you just downloaded. The same retrieval you ran before the',
    'reset will come back with the same top hit, down to the byte-identity',
    'of the brain id. The museum reopens.</p>',

    '<h3>Sharing a museum over the internet</h3>',
    '<p>Downloading a file and emailing it works, but Phase 3C adds a',
    'lighter-weight option: <strong>shareable URLs</strong>. You upload the',
    '<code>.vvarchive.json.gz</code> file to anywhere you can link to —',
    'a GitHub Gist raw URL, an S3 bucket, an IPFS gateway, your own',
    'server — and then anyone with the link can open it. We deliberately',
    'don\'t host anything: you own the URL, you can take it down any time,',
    'and we never see the bundle.</p>',

    '<p>The training panel grows three new buttons when',
    '<code>?snapshots=1</code> is on: <strong>📋 Copy shareable link</strong>',
    '(prompts you for your hosted URL and copies',
    '<code>?snapshots=1&amp;archive=&lt;your-url&gt;</code> to your',
    'clipboard), <strong>📎 Import from URL</strong> (fetches any URL and',
    'imports it), and a small <em>Community archives</em> list underneath.',
    'A friend who opens your share link auto-imports the bundle before the',
    'sim starts — they can warm-start from your population in one click.</p>',

    '<p>The community list ships empty-ish on purpose. There\'s exactly',
    'one placeholder entry pointing at <code>about:blank</code>. Adding a',
    'real archive to the gallery is an <em>external-scope</em> change: it',
    'puts a third-party URL into source control where everyone who opens',
    'the app will see it, so we require the project owner to sign off',
    'before any real URL lands. Until then the placeholder is a reminder',
    'of the shape — name, description, source — and a safe no-op for',
    'anyone poking at the UI.</p>',
  ].join('\n'),
};
